<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="configuracion">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="sitio_web" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="dominio" type="xs:string"></xs:element>
                            <xs:element name="tecnologias_utilizadas">
                                <xs:complexType>
                                    <xs:sequence>
                                    <xs:element name="tecnologia" type="xs:string" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="secciones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="seccion" type="xs:string" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="servidor">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="puerto" type="xs:integer"></xs:element>
                                        <xs:element name="bbdd" type="xs:string" maxOccurs="unbounded"></xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>